# Site settings
title: Yifeng Mei's blog
email: 
description: "Dairy of a Programmer"
baseurl: ""
url: "http://ssyifeng.github.io"
twitter_username: ssyfmei
github_username:  ssyfmei

# Build settings
markdown: kramdown
permalink: pretty

highlighter: rouge
kramdown:
  input: GFM
  auto_ids: true
  syntax_highlighter: rouge
