# Site settings
title: Yifeng Mei blog
email: 
description: "Daily Log of a Programmer."
baseurl: ""
url: "http://yfmei.github.io"
twitter_username: karpathy
github_username:  karpathy

# Build settings
markdown: kramdown
permalink: pretty

highlighter: rouge
kramdown:
  input: GFM
  auto_ids: true
  syntax_highlighter: rouge
